
-- заполняем склад

INSERT INTO STORE (NAME, PRICE, QUANTITY) VALUES ('Car', 1000, 10);
INSERT INTO STORE (NAME, PRICE, QUANTITY) VALUES ('Pistol', 50, 100);
INSERT INTO STORE (NAME, PRICE, QUANTITY) VALUES ('Pencil', 10, 1);